name: google_maps_webservice
description: Google Maps Web Services [API](https://developers.google.com/maps/web-services)
version: 0.0.20-nullsafety.5
homepage: https://github.com/lejard-h/google_maps_webservice

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  http: ^1.2.1
  json_annotation: ^4.8.1
  meta: ^1.14.0

dev_dependencies:
  build_runner: ^2.4.9
  coverage: ^1.7.2
  json_serializable: ^6.7.1
  test: ^1.24.3
